name: j1_logger
description: A logger for use throughout the J1 app.
version: 1.1.2
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  firebase_analytics: ^11.2.1
  get_it: ^8.0.2
  logger: ^2.4.0

dev_dependencies:
  j1_lints:
    git:
      url: https://github.com/J1-Apps/j1_lints.git
      ref: v1.0.2

  mocktail: ^1.0.4
  test: ^1.24.0
